<a href="https://colab.research.google.com/github/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/blob/main/QSAR_Part_3_Pubchem_Fingerprint_Calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Assignment-3**

## **AI and Drug Discovery Course: QSAR Modeling**

# **Descriptor Calculation**

## **Install PaDELpy**

In [1]:
!pip install padelpy

Collecting padelpy
  Downloading padelpy-0.1.16-py3-none-any.whl.metadata (7.7 kB)
Downloading padelpy-0.1.16-py3-none-any.whl (20.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.9/20.9 MB 42.5 MB/s eta 0:00:00
Installing collected packages: padelpy
Successfully installed padelpy-0.1.16

## **Import libraries**

In [2]:
import pandas as pd
import numpy as np
from google.colab import files
from padelpy import padeldescriptor

## **Load dataset**

In [4]:
df = pd.read_csv('df_lipinski.csv')
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL475818,active,7.119186,C#CC(C)(C)c1cc(N=C(C)C)cc(C(=O)Nc2ccc(C)c(C(=O...,452.558,5.91772,2.0,4.0
1,CHEMBL4203441,active,7.610834,C#CC(C)(C)c1cccc(C(=O)Nc2ccc(C)c(Nc3ccc4ncn(C)...,450.542,5.14862,2.0,4.0
2,CHEMBL3974840,active,7.000000,C#CCCC(=O)Nc1nc2ccc(C(=O)c3ccccc3C(=O)Nc3ccc(F...,454.461,4.53720,3.0,4.0
3,CHEMBL3905522,active,7.000000,C#CCCC(=O)Nc1nc2ccc(C3(O)c4ccccc4C(=O)N3Cc3ccc...,450.498,3.76420,3.0,4.0
4,CHEMBL3898105,active,7.000000,C#CCOC(=O)Nc1nc2cc(C3(O)c4ccccc4C(=O)N3Cc3cccc...,452.470,3.59400,3.0,5.0

In [5]:
data = df[['canonical_smiles', 'molecule_chembl_id']]
data.head()

                                    canonical_smiles molecule_chembl_id
0  C#CC(C)(C)c1cc(N=C(C)C)cc(C(=O)Nc2ccc(C)c(C(=O...       CHEMBL475818
1  C#CC(C)(C)c1cccc(C(=O)Nc2ccc(C)c(Nc3ccc4ncn(C)...      CHEMBL4203441
2  C#CCCC(=O)Nc1nc2ccc(C(=O)c3ccccc3C(=O)Nc3ccc(F...      CHEMBL3974840
3  C#CCCC(=O)Nc1nc2ccc(C3(O)c4ccccc4C(=O)N3Cc3ccc...      CHEMBL3905522
4  C#CCOC(=O)Nc1nc2cc(C3(O)c4ccccc4C(=O)N3Cc3cccc...      CHEMBL3898105

## **Convert to .smi format**

In [6]:
df_smi = data['canonical_smiles'].to_csv('smiles_chembl.smi', index=None, header=None)

In [7]:
! cat smiles_chembl.smi | head

C#CC(C)(C)c1cc(N=C(C)C)cc(C(=O)Nc2ccc(C)c(C(=O)Nc3cccnc3)c2)c1
C#CC(C)(C)c1cccc(C(=O)Nc2ccc(C)c(Nc3ccc4ncn(C)c(=O)c4c3)c2)c1
C#CCCC(=O)Nc1nc2ccc(C(=O)c3ccccc3C(=O)Nc3ccc(F)cc3)cc2[nH]1
C#CCCC(=O)Nc1nc2ccc(C3(O)c4ccccc4C(=O)N3Cc3ccccc3)cc2[nH]1
C#CCOC(=O)Nc1nc2cc(C3(O)c4ccccc4C(=O)N3Cc3ccccc3)ccc2[nH]1
C#Cc1c(F)ccc(N2C(=O)c3ccccc3C2(O)c2ccc3[nH]c(NC(=O)OC)nc3c2)c1F
C#Cc1c(Nc2c(F)ccc(NS(=O)(=O)CCC)c2Cl)ccc2ncn(C)c(=O)c12
C#Cc1cc(C)cc(N2C(=O)c3ccccc3C2(O)c2ccc3[nH]c(NC(=O)OC)nc3c2)c1
C#Cc1cc(Cl)cc(N2C(=O)c3ccccc3C2(O)c2ccc3[nH]c(NC(=O)OC)nc3c2)c1C
C#Cc1cc(N2C(=O)c3ccccc3C2(O)c2ccc3[nH]c(NC(=O)OC)nc3c2)c(F)cc1F

## **Calculate molecular Pubchem Fingerprints using "padeldescriptor" function**

In [8]:
padeldescriptor(mol_dir= "smiles_chembl.smi",
                d_file='pubchem_fingerprints.csv',
                fingerprints = True,
                retainorder= True,
                #removesalt = True, standardizetautomers = True, standardizenitro=True
                )

In [9]:
!ls -lh pubchem_fingerprints.csv

-rw-r--r-- 1 root root 11M Feb 22 16:33 pubchem_fingerprints.csv

In [10]:
df_fingerprint = pd.read_csv("pubchem_fingerprints.csv")
df_fingerprint.head()

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,AUTOGEN_smiles_chembl_1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AUTOGEN_smiles_chembl_2,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AUTOGEN_smiles_chembl_3,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AUTOGEN_smiles_chembl_4,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AUTOGEN_smiles_chembl_5,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Prepare Dataset for ML**

In [11]:
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL475818,active,7.119186,C#CC(C)(C)c1cc(N=C(C)C)cc(C(=O)Nc2ccc(C)c(C(=O...,452.558,5.91772,2.0,4.0
1,CHEMBL4203441,active,7.610834,C#CC(C)(C)c1cccc(C(=O)Nc2ccc(C)c(Nc3ccc4ncn(C)...,450.542,5.14862,2.0,4.0
2,CHEMBL3974840,active,7.000000,C#CCCC(=O)Nc1nc2ccc(C(=O)c3ccccc3C(=O)Nc3ccc(F...,454.461,4.53720,3.0,4.0
3,CHEMBL3905522,active,7.000000,C#CCCC(=O)Nc1nc2ccc(C3(O)c4ccccc4C(=O)N3Cc3ccc...,450.498,3.76420,3.0,4.0
4,CHEMBL3898105,active,7.000000,C#CCOC(=O)Nc1nc2cc(C3(O)c4ccccc4C(=O)N3Cc3cccc...,452.470,3.59400,3.0,5.0

In [12]:
# Select only the columns we need for ML
meta_cols = df[['molecule_chembl_id', 'bioactivity_class', 'pIC50']]

# Reset index to ensure proper alignment
meta_cols = meta_cols.reset_index(drop=True)
df_fingerprint = df_fingerprint.reset_index(drop=True)

# Combine meta data with fingerprints
combined_df = pd.concat([meta_cols, df_fingerprint.drop(df_fingerprint.columns[0], axis=1)], axis=1)

# Inspect the first few rows
combined_df.head()

,molecule_chembl_id,bioactivity_class,pIC50,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL475818,active,7.119186,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL4203441,active,7.610834,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL3974840,active,7.000000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL3905522,active,7.000000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL3898105,active,7.000000,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Save and download the dataset**

In [13]:
# Save as CSV
combined_df.to_csv("QSAR_dataset.csv", index=False)
print("Combined dataset saved as QSAR_dataset.csv")

# Download file in Colab
files.download("QSAR_dataset.csv")

Combined dataset saved as QSAR_dataset.csv